### ISSUE TITLE
warning message: File "/jasmine-core/jasmine.js" not found in module "jasmine-core".

### ISSUE THREAD

**Issue by ghernandez81** [mradionov/karma-jasmine-diff-reporter#20] opened 2016-10-20 20:18 UTC
I have this warning message tell me i can't use the pretty print option which i will like to use
here is all the karma plugin i have:
"jasmine-core": "2.5.2",
    "karma": "1.1.2",
    "karma-angular-filesort": "0.1.0",
    "karma-chrome-launcher": "1.0.1",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "1.0.2",
    "karma-jasmine-diff-reporter": "0.6.2",
    "karma-junit-reporter": "1.1.0",
    "karma-phantomjs-launcher": "1.0.1",
    "karma-threshold-reporter": "0.1.15",

**Comment by mradionov** [comment] 2016-10-20 21:18
Thanks, I'll take a look.

**Comment by mradionov** [comment] 2016-10-22 10:22
Do your tests work fine without karma-jasmine-diff-reporter? Do you use npm v2 or v3? Could you please also share your karma.conf.js?

**Comment by sajidali** [comment] 2016-12-13 07:08
I have same issue.
WARN [jasmine-diff]: File "/jasmine-core/jasmine.js" not found in module "jasmine-core".
WARN [jasmine-diff]: You may be using a not supported Jasmine version.
WARN [jasmine-diff]: Pretty print option will not be available

My npm version is 4.0.2, 
My installed modules are as follows:
    "jasmine-core": "^2.5.2",
    "karma": "^0.12.24",
    "karma-coverage": "~0.2.7",
    "karma-jasmine": "^0.2.3",
    "karma-jasmine-diff-reporter": "^0.6.3",
    "karma-phantomjs-launcher": "^0.1.4",

**Comment by mradionov** [comment] 2016-12-13 19:47
Thanks, @sajidali , I am able to reproduce the error for your particular case, it is because you use really old version of `karma-jasmine` which has been released almost 2,5 years ago. I guess I'll be able to land a fix for that, meanwhile you can try to upgrade `karma-jasmine` to version 0.3.0 or greater.

**Comment by mradionov** [comment] 2016-12-13 20:14
Yep, you definitely should upgrade karma-jasmine to 0.3.0, there is a ton of other bugs because of outdated Jasmine version, which was shipped with 0.2.3 version of karma-jasmine module. This upgrade should not break anything in your setup, I've just checked it with the details you have provided and it seems to work fine.
I won't bother with these fixes then because, there's a lot to fix and it does not really make sense to waste time on a compatibility with 2-year old release.

**Comment by sajidali** [comment] 2016-12-14 05:13
@mradionov  Thank you for checking this out. Will upgrade the `karma-jasmine` and let you know the results.

**Comment by sajidali** [comment] 2016-12-14 07:43
@mradionov  Thank you for checking this out. Will upgrade the `karma-jasmine` and let you know the results.

**Comment by sajidali** [comment] 2016-12-14 07:48
It is working now, with suggested upgrade, I upgraded to `karma-jasmine v0.3.8`. I think this issue can now be marked as resolved, as I've verified the upgrade to `karma-jasmine` solved the problem.

**Comment by mradionov** [comment] 2016-12-14 18:28
Glad to hear that it worked. I'll keep it open for a while though because I am not able to reproduce the original issue.

**Comment by mradionov** [comment] 2017-01-29 13:45
Unable to reproduce.
Feel free to reopen if you'll have any new information.

**Comment by tommck** [comment] 2019-08-29 12:03
I'm getting this same issue today.. latest jasmine-core, latest of this project, latest karma, etc.

npm  6.9.0
node 10.16.0

**Comment by mradionov** [comment] 2019-08-29 19:12
@tommck It would be great if you could share with me your package.json and karma.conf.js, either unchanged or reduced to a minimal reproducible state.

**Comment by tommck** [comment] 2019-08-31 14:45
@mradionov I'll try to get to that soon.  I have to VPN in to work to get that and the VPN is having issues. It might take until monday :(

**Comment by mradionov** [comment] 2019-10-04 20:37
Feel free to reopen if you will have more details for me

**Closed by mradionov** 2019-10-04 20:37 UTC
