### ISSUE TITLE
Option to remove the "Object()" in the diff view

### ISSUE THREAD

**Issue by ValentinH** [mradionov/karma-jasmine-diff-reporter#14] opened 2016-06-21 09:39 UTC
Do you think it would be possible to add an option that remove the "Object()" strings in the diff view. The goal is to display real JSON in the diff so it can be easily copy-pasted.

**Comment by mradionov** [comment] 2016-06-21 18:20
Sounds interesting, I'll give it a look. Thanks!

**Comment by mradionov** [comment] 2016-06-22 20:59
The problem is that not only objects are displayed differently

https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.js#L1729

Jasmine adds custom prefixes to other complex structures like functions, dates, html nodes and some special cases like <global>, <circular>, <getter>. All of these cases need to be transformed to JSON, but I believe it is not possible, because JSON does not support JS dates or functions or other complex structures. I guess that is the reason why Jasmine ended up with these prefixes. And fixing just objects does not seam right, because the rest of the things I've mentioned can easily break that JSON output.

**Comment by ValentinH** [comment] 2016-06-22 21:28
What I was thinking about was the display of the default dot-reporter which does display actual JSON. Unfortunately, I don't know how they achieve this

**Comment by mradionov** [comment] 2016-06-23 17:11
Are you talking about `dots` reporter shipped with Karma? For me it shows `Object({})` and the rest of Jasmine stuff. Could you please share your karma.conf and verions of packages, so I could reproduce it? Thanks.

**Comment by ValentinH** [comment] 2016-06-24 06:38
I just tried this morning, but I have Object() as well now. However, before switching to your tool, I was using an old version of jasmine-reporters and that's probably the reason.

I've found a SO question where a user shows its output and there are indeed no "Object()" strings: http://stackoverflow.com/questions/23676459/karma-jasmine-pretty-printing-object-comparison . Also, this answer is interesting (I can see that you already commented it a while ago ^^): http://stackoverflow.com/a/32280598/1713469

**Comment by mradionov** [comment] 2016-06-27 18:59
Thanks for the links. I guess I could try to add `JSON.stringify` somewhere, it will convert values to JSON as it supposed to do, bypassing Jasmine prettifier. It seems like the way to go to produce valid JSON, other options are too tricky.

**Comment by mradionov** [comment] 2016-07-03 16:43
Feature is released in [0.5.0](https://www.npmjs.com/package/karma-jasmine-diff-reporter).

You can find the docs here: https://github.com/mradionov/karma-jasmine-diff-reporter#json

It was a tough one. Thanks!

**Closed by mradionov** 2016-07-03 16:43 UTC

**Comment by ValentinH** [comment] 2016-07-04 13:52
Looks good to me! Thanks for this new feature! :+1:

**Comment by ValentinH** [comment] 2016-07-08 15:19
I'm sorry to bring a bug but I found one: if an object as undefined properties like `{a: 1, b: undefined}`, JSON.stringify will return  ̀{a: 1}`. In the default jasmine reporter, undefined values are also printed in the object.

**Comment by mradionov** [comment] 2016-07-08 17:38
I don't think it's a bug, `undefined` is not a supported value for JSON format. I would like to keep output compatible with JSON specs without bringing in any custom mixins.
